### ISSUE TITLE
Pro version not work

### ISSUE THREAD

**Issue by ditrim** [supercrypta/supercrypta.github.io#10]
Hi. I buy Pro version in AppStore, but Pro version not work, I still have basic version.
I click button Restore Purchase, I uninstall and install again, but nothing ((

**Comment by ricardo85x** [comment]
Hi
Thanks for using Super Crypta.
Could you try to go to:
About -> Buy Pro Version 
Again?

Maybe click multiple times on buy.

As you already bought it will be free.

The purchase response comes from Apple Server and maybe it was unstable at that time.

**Comment by ditrim** [comment]
All right. Pro version is worked!!!
