### ISSUE TITLE
Currency logo not displaying

### ISSUE THREAD

**Issue by mattyfew** [supercrypta/supercrypta.github.io#11]
I'm on MacOS High Sierra 10.13.3 and the currency logos have not been loading for a few weeks now. I thought I saw this fixed on a previous update, but it hasn't been working for me. All the spots where the logos should be are blank.

**Comment by ricardo85x** [comment]
Hi

Are you using SuperCrypta 0.73?

Could you try to close SuperCrypta From Menu, and open again?

Does bitcoin's image be blank too?

I found a bug but it should only happen some new coins like:

Bee Token 
Credits 
Sether 
Lympo 
Refereum 
IHT Real Estate Protocol
Bezop 
Rock 
Ink Protocol 
POA Network 
Experty 
Remme 
Arcblock 
Nucleus Vision
Copytrack 

I already sent a new version to apple to fix this coins and it will be released soon
