### ISSUE TITLE
Save screen estate

### ISSUE THREAD

**Issue by mamash** [supercrypta/supercrypta.github.io#3]
Please consider giving up some screen estate and cleaning up the display by making the collapsible controls completely optional. For tracking purposes, I couldn't care less for a calculator. The total hold should appear below the currency entries at the least, or maybe become an (optional) last entry on the list.

Ideally, the widget would be just the Market/Portfolio currency list for me.

**Comment by ricardo85x** [comment]
yep.
I am trying to find the ideal interface.
Probably I will create a preference menu somewhere. So the user will be able to enable/disable the calculator/total hold and make others adjustments.

**Comment by jaypearson2002** [comment]
Or maybe stop wasting your life away, spying on other people. Creepy sob

**Comment by ricardo85x** [comment]
Now the calculator/total hold can be disabled in settings.
