### ISSUE TITLE
Value entry/display doesn't respect locale

### ISSUE THREAD

**Issue by mamash** [supercrypta/supercrypta.github.io#4]
Please respect the macOS locale preferences for number entry/display. Decimal digits are ignored if entered with a comma separator (e.g. on a Czech or German locale).

Ideally, decimal and thousands separators should be rendered as per the current locale preferences, although this part may be argued over by other users.

**Comment by ricardo85x** [comment]
Thanks for the suggestion.
I corrected the locale problem.
I set the decimal separator to the current locale.
Also, numbers with thousand separators are valid.

It will be online soon
