### ISSUE TITLE
add/change buy price in portfolio

### ISSUE THREAD

**Issue by xonline** [supercrypta/supercrypta.github.io#7]
Please add "Bought price" in the portfolio..

I'm sure many people are in the same boat, they just wanna know is my portfolio/coin is up by $ or % from my bought price. Not just the value x today price.

Optional: Purchased date.

thank you.

**Comment by ricardo85x** [comment]
This sounds like a nice thing to have. I added it to our list of feature requests. 
Thank you for taking the time to share this with me!
